name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Permitir execução do gradlew
        run: chmod +x ./gradlew

      - name: Compilar o APK
        run: ./gradlew :Cadastro:assembleDebug

      - name: Salvar APK como artefato
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: Cadastro/build/outputs/apk/debug/Cadastro-debug.apk
